### ISSUE TITLE
Chinese characters

### ISSUE THREAD

**Issue by bobotan** [SyncfusionExamples/XlsIO-Examples#22]
When I tested this demo, when excel file contains  Chinese characters ,  I found that Chinese characters were not recognized

**Comment by SivakumarRamya** [comment]
Hi,

Greetings from Syncfusion.

Please share more information on the sample you have tried at your end. And, please share the issue reproducing the Excel document would help us to proceed further.

Regards,
Ramya.

**Comment by bobotan** [comment]
Thank you. The problem has been solved
